/**
 * GitHub Issues notification transport
 *
 * Uses GitHub Issues as a zero-budget notification transport.
 * Creates issues in a dedicated notifications repo or the user's own repo.
 */

import { fetchWithRetry, type FetchRetryOptions } from "../ingestor/fetch-retry.js";

export interface NotificationPayload {
  type: "new_mission" | "claimed" | "resolved" | "reopened";
  userLogin: string;
  repo: { owner: string; name: string };
  mission: {
    id: string;
    title: string;
    actionHint: string | null;
    compositeScore: number;
    effortLabel: string;
    dependency: { packageName: string; versionSpec: string };
    advisory: { osvId: string; severity: string; fixedVersion: string | null };
  };
}

export interface CreateIssueResult {
  success: boolean;
  issueNumber?: number | undefined;
  issueUrl?: string | undefined;
  error?: string | undefined;
}

/**
 * Creates a GitHub issue for a notification.
 * Uses the GH_DISPATCH_TOKEN (fine-grained PAT with issues:write on notifications repo)
 * or falls back to user's token if available.
 */
export async function createNotificationIssue(
  payload: NotificationPayload,
  githubToken: string | null,
  notificationsRepoOwner = "SpIob",
  notificationsRepoName = "DepTend-notifications",
  fetchRetryOptions: FetchRetryOptions = {},
): Promise<CreateIssueResult> {
  if (!githubToken) {
    return { success: false, error: "No GitHub token available for creating notification issue" };
  }

  const { type, userLogin, repo, mission } = payload;

  const title = `[${type.replace("_", " ").toUpperCase()}] ${repo.owner}/${repo.name}: ${mission.dependency.packageName} @ ${mission.dependency.versionSpec}`;

  const body = [
    `**Notification for @${userLogin}**`,
    "",
    `**Mission:** ${mission.title}`,
    `**Repository:** ${repo.owner}/${repo.name}`,
    `**Dependency:** ${mission.dependency.packageName} @ ${mission.dependency.versionSpec}`,
    `**Advisory:** ${mission.advisory.osvId} (${mission.advisory.severity.toUpperCase()})`,
    `**Fixed Version:** ${mission.advisory.fixedVersion ?? "Not yet published"}`,
    `**Composite Score:** ${mission.compositeScore.toFixed(1)} / 10`,
    `**Effort:** ${mission.effortLabel}`,
    "",
    mission.actionHint ? `**Action:** ${mission.actionHint}` : "",
    "",
    `---`,
    `*This notification was generated by DepTend. [View mission on DepTend](https://deptend.vercel.app/repo/${repo.owner}/${repo.name})*`,
  ]
    .filter(Boolean)
    .join("\n");

  const url = `https://api.github.com/repos/${notificationsRepoOwner}/${notificationsRepoName}/issues`;

  let response: Response;
  try {
    response = await fetchWithRetry(
      url,
      {
        method: "POST",
        headers: {
          Authorization: `Bearer ${githubToken}`,
          Accept: "application/vnd.github+json",
          "X-GitHub-Api-Version": "2022-11-28",
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ title, body, labels: [type, repo.owner] }),
      },
      { ...fetchRetryOptions, maxRetryAfterMs: 5000 },
    );
  } catch (err) {
    return { success: false, error: `Network error: ${String(err)}` };
  }

  if (!response.ok) {
    const errorText = await response.text().catch(() => "Unknown error");
    return { success: false, error: `GitHub API error ${String(response.status)}: ${errorText}` };
  }

  const data = (await response.json().catch(() => ({}))) as { number?: number; html_url?: string };
  return {
    success: true,
    issueNumber: data.number,
    issueUrl: data.html_url,
  };
}

/**
 * Builds a notification payload for a mission event.
 */
export function buildNotificationPayload(
  type: "new_mission" | "claimed" | "resolved" | "reopened",
  userLogin: string,
  repo: { owner: string; name: string },
  mission: {
    id: string;
    title: string;
    actionHint: string | null;
    compositeScore: number;
    effortLabel: string;
    dependency: { packageName: string; versionSpec: string };
    advisory: { osvId: string; severity: string; fixedVersion: string | null };
  },
): NotificationPayload {
  return { type, userLogin, repo, mission };
}
